/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Red_Market;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author NKSingh
 */
public class App_Start extends javax.swing.JFrame {
    Connection con=null;
Statement stmt=null;
ResultSet rs=null;


    /** Creates new form iMarketMain */
    public App_Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        imanl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ml = new javax.swing.JLabel();
        ll = new javax.swing.JLabel();
        cl = new javax.swing.JLabel();
        bl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        keyl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RedMarket");
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 5, true), new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 5, true)));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);

        imanl.setForeground(new java.awt.Color(240, 240, 240));
        imanl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imanl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/zironmanactive.png"))); // NOI18N
        imanl.setToolTipText("");
        imanl.setAlignmentY(0.0F);
        imanl.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/zironman.png"))); // NOI18N
        imanl.setEnabled(false);
        imanl.setFocusable(false);
        imanl.setIconTextGap(0);
        imanl.setInheritsPopupMenu(false);
        imanl.setRequestFocusEnabled(false);
        imanl.setVerifyInputWhenFocusTarget(false);
        imanl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imanlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imanlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imanlMouseExited(evt);
            }
        });

        ml.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        ml.setForeground(new java.awt.Color(255, 0, 0));
        ml.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/mobicoactive.png"))); // NOI18N
        ml.setToolTipText("");
        ml.setAlignmentY(0.0F);
        ml.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/mobico.png"))); // NOI18N
        ml.setEnabled(false);
        ml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mlMouseExited(evt);
            }
        });

        ll.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        ll.setForeground(new java.awt.Color(255, 0, 0));
        ll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/laptopactive.png"))); // NOI18N
        ll.setAlignmentY(0.0F);
        ll.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/laptopico.png"))); // NOI18N
        ll.setEnabled(false);
        ll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llMouseExited(evt);
            }
        });

        cl.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        cl.setForeground(new java.awt.Color(255, 0, 0));
        cl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/caractive.png"))); // NOI18N
        cl.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/carico.png"))); // NOI18N
        cl.setEnabled(false);
        cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clMouseExited(evt);
            }
        });

        bl.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        bl.setForeground(new java.awt.Color(255, 0, 0));
        bl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/bikeactive.png"))); // NOI18N
        bl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bl.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/bikeico.png"))); // NOI18N
        bl.setEnabled(false);
        bl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ml, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                    .addComponent(cl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ml, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ll, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bl, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Feel the Best Quality And Fetch up huge Quantity");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Mainheading.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("EMAIL: RedMarket@gmail.com");

        keyl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        keyl.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("WEBSITE: RedMarket.com");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("CONTACT-9958283193 ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(keyl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(keyl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/exit2.png"))); // NOI18N
        jButton2.setToolTipText("Exit App");
        jButton2.setAlignmentY(0.0F);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/exit1.png"))); // NOI18N
        jButton2.setEnabled(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/home (3).png"))); // NOI18N
        jButton1.setToolTipText("Home");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/home (2).png"))); // NOI18N
        jButton1.setEnabled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(imanl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imanl, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imanlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imanlMouseClicked
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

    }//GEN-LAST:event_imanlMouseClicked

    private void imanlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imanlMouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        keyl.setText(""+"20% Discount on App");
        

    }//GEN-LAST:event_imanlMouseEntered

    private void imanlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imanlMouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

    }//GEN-LAST:event_imanlMouseExited

    private void mlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mlMouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        ml.setEnabled(true);
        keyl.setText(""+"Mobile Store");
        
    }//GEN-LAST:event_mlMouseEntered

    private void mlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mlMouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        ml.setEnabled(false);

        keyl.setText(""+"");

    }//GEN-LAST:event_mlMouseExited

    private void mlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mlMouseClicked
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        keyl.setText(""+"You Have To Visit Home First");
    }//GEN-LAST:event_mlMouseClicked

    private void llMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llMouseClicked
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        keyl.setText(""+"You Have To Visit Home First");

    }//GEN-LAST:event_llMouseClicked

    private void llMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llMouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        ll.setEnabled(true);
        keyl.setText(""+"Laptops Store");
    }//GEN-LAST:event_llMouseEntered

    private void llMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llMouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        ll.setEnabled(false);

    }//GEN-LAST:event_llMouseExited

    private void clMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clMouseClicked
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        keyl.setText(""+"You Have To Visit Home First");
    }//GEN-LAST:event_clMouseClicked

    private void clMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clMouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        cl.setEnabled(true);
        keyl.setText(""+"Cars Store");
    }//GEN-LAST:event_clMouseEntered

    private void clMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clMouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        cl.setEnabled(false);

    }//GEN-LAST:event_clMouseExited

    private void blMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blMouseClicked
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        keyl.setText(""+"You Have To Visit Home First");
    }//GEN-LAST:event_blMouseClicked

    private void blMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blMouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        bl.setEnabled(true);
        keyl.setText(""+"Bikes Store");
    }//GEN-LAST:event_blMouseEntered

    private void blMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blMouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        bl.setEnabled(false);

    }//GEN-LAST:event_blMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        imanl.setEnabled(true);
        
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        imanl.setEnabled(false);
        
    }//GEN-LAST:event_jLabel2MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton2.setEnabled(true);
        imanl.setEnabled(true);
        keyl.setText(""+"Exit from App");
        

    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton2.setEnabled(false);
        keyl.setText(""+"");
        imanl.setEnabled(false);

    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        //jButton2.setIcon(new ImageIcon("D:\\Red_Market\\src\\Red_Market\\Images\\exit3.png"));

    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
       // jButton2.setIcon(new ImageIcon("D:\\Red_Market\\src\\Red_Market\\Images\\exit2.png"));
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
       // jButton1.setIcon(new ImageIcon("D:\\Red_Market\\src\\Red_Market\\Images\\home (2).png"));

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton1.setEnabled(true);
        keyl.setText(""+"iMarket Home");
        imanl.setEnabled(true);
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton1.setEnabled(false);
        keyl.setText(""+"");
        imanl.setEnabled(false);
        
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
       // jButton1.setIcon(new ImageIcon("D:\\Red_Market\\src\\Red_Market\\Images\\home1.png"));
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
       // jButton1.setIcon(new ImageIcon("D:\\Red_Market\\src\\Red_Market\\Images\\home (3).png"));
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        new BD_Home().setVisible(true);
        try
        {
            Class.forName("java.sql.Driver");
            con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/redmarket","root","nishant");

            System.out.print("successsss");

        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Error in Connectivity","Error", 1);
            e.printStackTrace();

        }
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
         
  
    }//GEN-LAST:event_jPanel4MouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        
    }//GEN-LAST:event_formMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App_Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App_Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App_Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App_Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App_Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bl;
    private javax.swing.JLabel cl;
    private javax.swing.JLabel imanl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel keyl;
    private javax.swing.JLabel ll;
    private javax.swing.JLabel ml;
    // End of variables declaration//GEN-END:variables
}
