/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Red_Market;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author NKSingh
 */
public class BD_Home extends javax.swing.JFrame {
    Connection con=null;
    Statement stmt=null;
    ResultSet rs=null;

    /**
     * Creates new form NewJFrame
     */
    public BD_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ml = new javax.swing.JLabel();
        ll = new javax.swing.JLabel();
        cl = new javax.swing.JLabel();
        bl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        contact = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pwdfld = new javax.swing.JPasswordField();
        dbtnn = new javax.swing.JButton();
        sbtnn = new javax.swing.JButton();
        vbtnn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        subtnn = new javax.swing.JButton();
        qubtnn = new javax.swing.JButton();
        statbtnn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();
        homeico = new javax.swing.JLabel();
        exitl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);

        ml.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        ml.setForeground(new java.awt.Color(255, 0, 0));
        ml.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/MOBICO (1).png"))); // NOI18N
        ml.setAlignmentY(0.0F);
        ml.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ml.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/MOBICO (2).png"))); // NOI18N
        ml.setEnabled(false);
        ml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mlMouseExited(evt);
            }
        });

        ll.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        ll.setForeground(new java.awt.Color(255, 0, 0));
        ll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/LAPICO (1).png"))); // NOI18N
        ll.setAlignmentY(0.0F);
        ll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ll.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/LAPICO (2).png"))); // NOI18N
        ll.setEnabled(false);
        ll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llMouseExited(evt);
            }
        });

        cl.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        cl.setForeground(new java.awt.Color(255, 0, 0));
        cl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/CARICO (1).png"))); // NOI18N
        cl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cl.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/images/CARICO (2).png"))); // NOI18N
        cl.setEnabled(false);
        cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clMouseExited(evt);
            }
        });

        bl.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        bl.setForeground(new java.awt.Color(255, 0, 0));
        bl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/BIKEICO (2).png"))); // NOI18N
        bl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bl.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/BIKEICO (1).png"))); // NOI18N
        bl.setEnabled(false);
        bl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Mainheading.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/bike - Copy.png"))); // NOI18N
        jButton4.setToolTipText("Bikes Store");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/bike.png"))); // NOI18N
        jButton4.setEnabled(false);
        jButton4.setFocusPainted(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/lapptop - Copy.png"))); // NOI18N
        jButton2.setToolTipText("Laptops Store");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/lapptop.png"))); // NOI18N
        jButton2.setEnabled(false);
        jButton2.setFocusPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/mob - Copy.png"))); // NOI18N
        jButton1.setToolTipText("Mobiles Store");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/mob.png"))); // NOI18N
        jButton1.setEnabled(false);
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/caract.png"))); // NOI18N
        jButton3.setToolTipText("Cars Store");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/car.png"))); // NOI18N
        jButton3.setEnabled(false);
        jButton3.setFocusPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Contacts-Group-Silver-icon - Copy.png"))); // NOI18N
        contact.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Contacts-Group-Silver-icon.png"))); // NOI18N
        contact.setEnabled(false);
        contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Seller's Panel"));

        jLabel3.setText("Password");

        pwdfld.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pwdfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdfldActionPerformed(evt);
            }
        });
        pwdfld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdfldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwdfldKeyReleased(evt);
            }
        });

        dbtnn.setText("Delete");
        dbtnn.setEnabled(false);
        dbtnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbtnnActionPerformed(evt);
            }
        });

        sbtnn.setText("Search");
        sbtnn.setEnabled(false);
        sbtnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbtnnActionPerformed(evt);
            }
        });

        vbtnn.setText("View All");
        vbtnn.setEnabled(false);
        vbtnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbtnnActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/login (2).png"))); // NOI18N

        subtnn.setText("Simple Update");
        subtnn.setEnabled(false);
        subtnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtnnActionPerformed(evt);
            }
        });

        qubtnn.setText("Query Update");
        qubtnn.setEnabled(false);
        qubtnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qubtnnActionPerformed(evt);
            }
        });

        statbtnn.setText("Statistics");
        statbtnn.setEnabled(false);
        statbtnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statbtnnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vbtnn, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(dbtnn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sbtnn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qubtnn, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(statbtnn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subtnn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pwdfld)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(sbtnn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vbtnn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbtnn, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(subtnn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qubtnn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statbtnn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/imaskact.png"))); // NOI18N
        jLabel1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/imask.png"))); // NOI18N
        jLabel1.setEnabled(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(lab, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        homeico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/HOMEIC (1).png"))); // NOI18N
        homeico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeico.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/HOMEIC (2).png"))); // NOI18N
        homeico.setEnabled(false);
        homeico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeicoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeicoMouseExited(evt);
            }
        });

        exitl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/EXITICO (2).png"))); // NOI18N
        exitl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitl.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/EXITICO (1).png"))); // NOI18N
        exitl.setEnabled(false);
        exitl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitlMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bl, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(cl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ml, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ll, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeico, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1032, 1032, 1032))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setAlignmentY(0.8F);

        jMenu1.setForeground(new java.awt.Color(255, 51, 51));
        jMenu1.setText("File");
        jMenu1.setAlignmentX(2.0F);
        jMenu1.setAlignmentY(0.8F);
        jMenu1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenu1.setIconTextGap(10);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem2.setText("Start App Again");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem3.setText("Home Screen");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem4.setText("Mobiles");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem5.setText("Laptops");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem6.setText("Cars");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem7.setText("Bikes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem30.setText("Email");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem30);

        jMenuItem31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem31.setText("Mobile Helpline");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem31);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem12.setText("Like us on Facebook");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem25.setText("Exit Current Window");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem25);

        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem26.setText("Shutdown App");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem26);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 51, 51));
        jMenu2.setText("Dealers");
        jMenu2.setAlignmentX(9.0F);
        jMenu2.setAlignmentY(0.8F);
        jMenu2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenu2.setIconTextGap(10);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem15.setText("View All Records");
        jMenuItem15.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem15.setEnabled(false);
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem22.setText("Search Record");
        jMenuItem22.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem22.setEnabled(false);
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem22);

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem21.setText("Delete Record");
        jMenuItem21.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem21.setEnabled(false);
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem21);

        jMenuItem27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem27.setText("Simple Update");
        jMenuItem27.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem27.setEnabled(false);
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem27);

        jMenuItem28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem28.setText("Query Update");
        jMenuItem28.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem28.setEnabled(false);
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem28);

        jMenuItem29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem29.setText("Statistics");
        jMenuItem29.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem29.setEnabled(false);
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem29);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(255, 51, 51));
        jMenu3.setText("Buyer");
        jMenu3.setAlignmentY(0.8F);
        jMenu3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenu3.setIconTextGap(10);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem20.setText("Home Screen");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem20);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem19.setText("Mobiles");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem18.setText("Laptops");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem18);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem16.setText("Cars");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem16);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem17.setText("Bikes");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jMenuBar1.add(jMenu3);

        jMenu7.setForeground(new java.awt.Color(255, 51, 51));
        jMenu7.setText("Contact");
        jMenu7.setAlignmentY(0.8F);
        jMenu7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenu7.setIconTextGap(10);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem9.setText("Like us on Facebook");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem23.setText("Email");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem23);

        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem24.setText("Mobile");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem24);

        jMenuBar1.add(jMenu7);

        jMenu8.setForeground(new java.awt.Color(255, 51, 51));
        jMenu8.setText("Exit");
        jMenu8.setAlignmentX(9.0F);
        jMenu8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenu8.setIconTextGap(10);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem10.setText("Exit Current Window");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_Market/Images/Red_Button_279212905_std_835.png"))); // NOI18N
        jMenuItem11.setText("Shutdown App");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        new D_search_delete().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        System.exit(0);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void mlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mlMouseClicked
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        new B_Mobiles().setVisible(true);
        dispose();
    }//GEN-LAST:event_mlMouseClicked

    private void mlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mlMouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        ml.setEnabled(true);

    }//GEN-LAST:event_mlMouseEntered

    private void mlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mlMouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        ml.setEnabled(false);
        ml.setToolTipText(""+"Mobile Store");

    }//GEN-LAST:event_mlMouseExited

    private void llMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llMouseClicked
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        new B_Laptops().setVisible(true);
        dispose();
    }//GEN-LAST:event_llMouseClicked

    private void llMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llMouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        ll.setToolTipText(""+"Laptops Store");
        ll.setEnabled(true);

    }//GEN-LAST:event_llMouseEntered

    private void llMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llMouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        ll.setEnabled(false);
    }//GEN-LAST:event_llMouseExited

    private void clMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clMouseClicked
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        new B_Cars().setVisible(true);
        dispose();
    }//GEN-LAST:event_clMouseClicked

    private void clMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clMouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        cl.setToolTipText(""+"Cars Store");
        cl.setEnabled(true);

    }//GEN-LAST:event_clMouseEntered

    private void clMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clMouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        cl.setEnabled(false);
    }//GEN-LAST:event_clMouseExited

    private void blMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blMouseClicked
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        new B_Bikes().setVisible(true);
        dispose();
    }//GEN-LAST:event_blMouseClicked

    private void blMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blMouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        bl.setToolTipText(""+"Bikes Store");
        bl.setEnabled(true);

    }//GEN-LAST:event_blMouseEntered

    private void blMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blMouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

        bl.setEnabled(false);
    }//GEN-LAST:event_blMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        // imanl.setEnabled(true);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        // imanl.setEnabled(false);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton4.setEnabled(true);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton4.setEnabled(false);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton4.setEnabled(true);
        new B_Bikes().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        new B_Laptops().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton1.setEnabled(true);
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton1.setEnabled(false);
        
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        new B_Mobiles().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton3.setEnabled(true);
        
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jButton3.setEnabled(false);
        
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        new B_Cars().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pwdfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdfldActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
    }//GEN-LAST:event_pwdfldActionPerformed

    private void pwdfldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdfldKeyPressed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com

    }//GEN-LAST:event_pwdfldKeyPressed

    private void pwdfldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdfldKeyReleased
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        String pwd=new String(pwdfld.getPassword());
        if (pwd.equals("nishant"))
        {statbtnn.setEnabled(true);
        qubtnn.setEnabled(true);
        subtnn.setEnabled(true);
            dbtnn.setEnabled(true);
            sbtnn.setEnabled(true);
            vbtnn.setEnabled(true);
            jMenuItem15.setEnabled(true);
            jMenuItem21.setEnabled(true);
            jMenuItem22.setEnabled(true);
            jMenuItem27.setEnabled(true);
            jMenuItem28.setEnabled(true);
            jMenuItem29.setEnabled(true);
        }
        else
        {jMenuItem15.setEnabled(false);
            jMenuItem21.setEnabled(false);
            jMenuItem22.setEnabled(false);
            jMenuItem27.setEnabled(false);
            jMenuItem28.setEnabled(false);
            jMenuItem29.setEnabled(false);
            statbtnn.setEnabled(false);
            dbtnn.setEnabled(false);
            sbtnn.setEnabled(false);
            vbtnn.setEnabled(false);
            subtnn.setEnabled(false);
            qubtnn.setEnabled(false);

        }
    }//GEN-LAST:event_pwdfldKeyReleased

    private void dbtnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbtnnActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        new D_search_delete().setVisible(true);
        dispose();
    }//GEN-LAST:event_dbtnnActionPerformed

    private void sbtnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbtnnActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        new D_search_delete().setVisible(true);
        dispose();
    }//GEN-LAST:event_sbtnnActionPerformed

    private void vbtnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbtnnActionPerformed
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        new D_search_delete().setVisible(true);
        dispose();
    }//GEN-LAST:event_vbtnnActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jLabel1.setEnabled(true);
        
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        jLabel1.setEnabled(false);
        
    }//GEN-LAST:event_jLabel1MouseExited

    private void homeicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeicoMouseClicked
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        new BD_Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeicoMouseClicked

    private void homeicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeicoMouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        homeico.setEnabled(true);
        
    }//GEN-LAST:event_homeicoMouseEntered

    private void homeicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeicoMouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        homeico.setEnabled(false);
        
    }//GEN-LAST:event_homeicoMouseExited

    private void exitlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlMouseClicked
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        
        dispose();
    }//GEN-LAST:event_exitlMouseClicked

    private void exitlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlMouseEntered
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        exitl.setEnabled(true);
        
    }//GEN-LAST:event_exitlMouseEntered

    private void exitlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlMouseExited
        // TODO add code here: CopyRight: nishant.nksingh@gmail.com
        exitl.setEnabled(false);
    }//GEN-LAST:event_exitlMouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jPanel3MouseExited

    private void contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseClicked
        // TODO add your handling code here:
        new Contact_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_contactMouseClicked

    private void contactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseEntered
        // TODO add your handling code here:
        contact.setEnabled(true);
    }//GEN-LAST:event_contactMouseEntered

    private void contactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseExited
        // TODO add your handling code here:
         contact.setEnabled(false);
    }//GEN-LAST:event_contactMouseExited

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new Contact_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        new Contact_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
        new Contact_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void subtnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtnnActionPerformed
        // TODO add your handling code here:
        new D_Simple_Update().setVisible(true);
        dispose();
    }//GEN-LAST:event_subtnnActionPerformed

    private void qubtnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qubtnnActionPerformed
        // TODO add your handling code here:
        new D_Query_Update().setVisible(true);
        dispose();
    }//GEN-LAST:event_qubtnnActionPerformed

    private void statbtnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statbtnnActionPerformed
        // TODO add your handling code here:
        new Statistics().setVisible(true);
        dispose();
    }//GEN-LAST:event_statbtnnActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        new B_Cars().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        new B_Bikes().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        new B_Laptops().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        new B_Mobiles().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        new BD_Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new App_Start().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new BD_Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new B_Mobiles().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new B_Laptops().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new B_Cars().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new B_Bikes().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
        new D_Query_Update().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new Contact_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        // TODO add your handling code here:
        new Contact_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        // TODO add your handling code here:
        new Contact_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        new D_search_delete().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        new D_search_delete().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        new D_Simple_Update().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
        new Statistics().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BD_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BD_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BD_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BD_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BD_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bl;
    private javax.swing.JLabel cl;
    private javax.swing.JLabel contact;
    private javax.swing.JButton dbtnn;
    private javax.swing.JLabel exitl;
    private javax.swing.JLabel homeico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel ll;
    private javax.swing.JLabel ml;
    private javax.swing.JPasswordField pwdfld;
    private javax.swing.JButton qubtnn;
    private javax.swing.JButton sbtnn;
    private javax.swing.JButton statbtnn;
    private javax.swing.JButton subtnn;
    private javax.swing.JButton vbtnn;
    // End of variables declaration//GEN-END:variables
}
